version: "3.3"
services:

  mysql-local:
    image: mysql:8.0.17
    env_file: ./.env
    environment:
    - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT


  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9090:80
    environment:
      - PMA_ARBITRARY=1

  app:
    depends_on:
      - mysql-local
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://34.141.184.90/bandmate-auth",
          "spring.datasource.username" : "$MYSQLDB_USER",
          "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
          "spring.jpa.hibernate.ddl-auto" : "update",
          "bezkoder.app.jwtCookieName" : "bezkoder",
          "bezkoder.app.jwtSecret" : "bezKoderSecretKey",
          "bezkoder.app.jwtExpirationMs" : "86400000"
        }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true